/* schema.c for ObTheme
   Copyright (c) 2026  NetLinux

   The key/type/default/description/see-also documentation table below is
   adapted from themeElements in the original ObTheme by Xyne (2009) and
   its forks (credited to ikem-krueger, github.com/ohitsdylan/obtheme),
   used here with credit under GPLv2 terms matching the original project.
   The C data structure, parser, and every other file in this project are
   an original implementation, cross-checked against the authoritative
   parsing logic in /Data/openbox/obrender/theme.c (read_int/read_color/
   read_appearance/read_button_styles).

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License (version 2) as
   published by the Free Software Foundation.
*/

#include "schema.h"
#include <string.h>

const ThemeKeySpec THEME_SCHEMA[] = {
    { "border.color", TK_COLOR, "#000000", 0, 0, "This property is obsolete and only present for backwards compatibility.", { "window.active.border.color", "window.inactive.border.color", "menu.border.color", NULL } },
    { "border.width", TK_INT, "1", 0, 100, "Specifies the size of the border drawn around window frames.", { "window.active.border.color", "window.inactive.border.color", NULL, NULL } },
    { "menu.border.color", TK_COLOR, "window.active.border.color", 0, 0, "Specifies the border color for menus.", { "menu.border.width", NULL, NULL, NULL } },
    { "menu.border.width", TK_INT, "border.width", 0, 100, "Specifies the size of the border drawn around menus.", { "menu.border.color", NULL, NULL, NULL } },
    { "menu.items.active.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for the selected menu entry (whether or not it is disabled). When it is parentrelative, then it uses the menu.items.bg which is underneath it.", { "menu.items.bg", NULL, NULL, NULL } },
    { "menu.items.active.disabled.text.color", TK_COLOR, "menu.items.disabled.text.color", 0, 0, "Specifies the text color for disabled menu entries when they are selected.", { NULL, NULL, NULL, NULL } },
    { "menu.items.active.text.color", TK_COLOR, "#000000", 0, 0, "Specifies the text color for normal menu entries when they are selected.", { NULL, NULL, NULL, NULL } },
    { "menu.items.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for menus.", { "menu.items.active.bg", NULL, NULL, NULL } },
    { "menu.items.disabled.text.color", TK_COLOR, "#000000", 0, 0, "Specifies the text color for disabled menu entries.", { NULL, NULL, NULL, NULL } },
    { "menu.items.font", TK_FONT_SHADOW, "shadow=n", 0, 0, "Specifies the shadow for all menu entries.", { NULL, NULL, NULL, NULL } },
    { "menu.items.text.color", TK_COLOR, "#FFFFFF", 0, 0, "Specifies the text color for normal menu entries.", { NULL, NULL, NULL, NULL } },
    { "menu.overlap", TK_INT, "0", -100, 100, "This property is obsolete and only present for backwards compatibility.", { "menu.overlap.x", "menu.overlap.y", NULL, NULL } },
    { "menu.overlap.x", TK_INT, "menu.overlap", -100, 100, "Specifies how sub menus should overlap their parents. A positive value moves the submenu over top of their parent by that amount. A negative value moves the submenu away from their parent by that amount. (As of version 3.4.7)", { "menu.overlap.y", NULL, NULL, NULL } },
    { "menu.overlap.y", TK_INT, "menu.overlap", -100, 100, "Specifies how sub menus should be positioned relative to their parents. A positive value moves the submenu vertically down by that amount, a negative value moves it up by that amount. (As of version 3.4.7)", { "menu.overlap.x", NULL, NULL, NULL } },
    { "menu.separator.color", TK_COLOR, "menu.items.text.color", 0, 0, "The color of menu line separators. (As of version 3.4.7)", { "menu.items.text.color", NULL, NULL, NULL } },
    { "menu.separator.padding.height", TK_INT, "3", 0, 100, "Specifies the space on the top and bottom of menu line separators. (As of version 3.4.7)", { "menu.separator.padding.width", NULL, NULL, NULL } },
    { "menu.separator.padding.width", TK_INT, "6", 0, 100, "Specifies the space on the left and right side of menu line separators. (As of version 3.4.7)", { "menu.separator.padding.height", NULL, NULL, NULL } },
    { "menu.separator.width", TK_INT, "1", 1, 100, "Specifies the size of menu line separators. (As of version 3.4.7)", { NULL, NULL, NULL, NULL } },
    { "menu.title.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for menu headers. When it is parentrelative, then it uses the menu.items.bg which is underneath it.", { "menu.items.bg", NULL, NULL, NULL } },
    { "menu.title.text.color", TK_COLOR, "#000000", 0, 0, "Specifies the text color for menu headers.", { NULL, NULL, NULL, NULL } },
    { "menu.title.text.font", TK_FONT_SHADOW, "shadow=n", 0, 0, "Specifies the shadow for all menu headers.", { NULL, NULL, NULL, NULL } },
    { "menu.title.text.justify", TK_JUSTIFY, "Left", 0, 0, "Specifies how text is aligned in all menu headers.", { NULL, NULL, NULL, NULL } },
    { "osd.bg", TK_TEXTURE, "window.active.title.bg", 0, 0, "Specifies the background for on-screen-dialogs, such as the focus cycling (Alt-Tab) dialog.", { NULL, NULL, NULL, NULL } },
    { "osd.border.color", TK_COLOR, "window.active.border.color", 0, 0, "Specifies the border color for on-screen-dialogs, such as the focus cycling (Alt-Tab) dialog.", { "osd.border.width", NULL, NULL, NULL } },
    { "osd.border.width", TK_INT, "border.width", 0, 100, "Specifies the size of the border drawn on-screen-dialogs, such as the focus cycling (Alt-Tab) dialog.", { "osd.border.color", NULL, NULL, NULL } },
    { "osd.hilight.bg", TK_TEXTURE, "window.active.label.bg, if it is not parentrelative. Otherwise, window.active.title.bg", 0, 0, "Specifies the texture for the selected desktop in the desktop cycling (pager) dialog.", { NULL, NULL, NULL, NULL } },
    { "osd.label.bg", TK_TEXTURE, "window.active.label.bg", 0, 0, "Specifies the background for text in on-screen-dialogs, such as the focus cycling (Alt-Tab) dialog.", { NULL, NULL, NULL, NULL } },
    { "osd.label.text.color", TK_COLOR, "#000000", 0, 0, "Specifies the text color for on-screen-dialogs, such as the focus cycling (Alt-Tab) dialog.", { NULL, NULL, NULL, NULL } },
    { "osd.label.text.font", TK_FONT_SHADOW, "shadow=n", 0, 0, "Specifies the text shadow for on-screen-dialogs, such as the focus cycling (Alt-Tab) dialog.", { NULL, NULL, NULL, NULL } },
    { "osd.unhilight.bg", TK_TEXTURE, "window.inactive.label.bg, if it is not parentrelative. Otherwise, window.inactive.title.bg", 0, 0, "Specifies the texture for unselected desktops in the desktop cycling (pager) dialog.", { NULL, NULL, NULL, NULL } },
    { "padding.height", TK_INT, "padding.width", 0, 100, "Specifies the padding size, used for spacing out elements in the window decorations. This can be used to give a theme a more compact or a more relaxed feel. This specifies padding in only the vertical direction.", { "padding.width", NULL, NULL, NULL } },
    { "padding.width", TK_INT, "3", 0, 100, "Specifies the padding size, used for spacing out elements in the window decorations. This can be used to give a theme a more compact or a more relaxed feel. This specifies padding in the horizontal direction (and vertical direction if padding.height is not explicitly set).", { "padding.height", NULL, NULL, NULL } },
    { "window.active.border.color", TK_COLOR, "border.color", 0, 0, "Specifies the border color for the focused window.", { "border.width", "window.inactive.border.color", NULL, NULL } },
    { "window.active.button.disabled.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for titlebar buttons when they are disabled for the window. This element is for the focused window. When it is parentrelative, then it uses the window.active.title.bg which is underneath it.", { "titlebar colors", "window.active.title.bg", "window.inactive.button.disabled.bg", NULL } },
    { "window.active.button.disabled.image.color", TK_COLOR, "#FFFFFF", 0, 0, "Specifies the color of the images in titlebar buttons when they are disabled for the window. This element is for the focused window.", { "window.inactive.button.disabled.image.color", NULL, NULL, NULL } },
    { "window.active.button.hover.bg", TK_TEXTURE, "window.active.button.unpressed.bg", 0, 0, "Specifies the background for titlebar buttons when the mouse is over them. This element is for the focused window. When it is parentrelative, then it uses the window.active.title.bg which is underneath it.", { "titlebar colors", "window.active.title.bg", "window.inactive.button.hover.bg", NULL } },
    { "window.active.button.hover.image.color", TK_COLOR, "window.active.button.unpressed.image.color", 0, 0, "Specifies the color of the images in titlebar buttons when the mouse is over top of the button. This element is for the focused window.", { "window.inactive.button.hover.image.color", NULL, NULL, NULL } },
    { "window.active.button.pressed.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for titlebar buttons when they are being pressed by the user. This element is for the focused window. When it is parentrelative, then it uses the window.active.title.bg which is underneath it.", { "titlebar colors", "window.active.title.bg", "window.inactive.button.pressed.bg", NULL } },
    { "window.active.button.pressed.image.color", TK_COLOR, "window.active.button.unpressed.image.color", 0, 0, "Specifies the color of the images in titlebar buttons when they are being pressed by the user. This element is for the focused window.", { "window.inactive.button.pressed.image.color", NULL, NULL, NULL } },
    { "window.active.button.toggled.bg", TK_TEXTURE, "window.active.button.pressed.bg", 0, 0, "This property is obsolete and only present for backwards compatibility.", { NULL, NULL, NULL, NULL } },
    { "window.active.button.toggled.hover.bg", TK_TEXTURE, "window.active.button.toggled.unpressed.bg", 0, 0, "Specifies the default background for titlebar buttons if the user is pressing them with the mouse while they are toggled - such as when a window is maximized. This element is for the focused window. When it is parentrelative, then it uses the window.inactive.title.bg which is underneath it.", { "titlebar colors", "window.active.title.bg", "window.inactive.button.toggled.hover.bg", NULL } },
    { "window.active.button.toggled.hover.image.color", TK_COLOR, "window.active.button.toggled.unpressed.image.color", 0, 0, "Specifies the color of the images in the titlebar buttons when the mouse is hovered over them while they are in the toggled state - such as when a window is maximized. This element is for the focused window.", { "window.inactive.button.toggled.hover.image.color", NULL, NULL, NULL } },
    { "window.active.button.toggled.image.color", TK_COLOR, "window.active.button.pressed.image.color", 0, 0, "This property is obsolete and only present for backwards compatibility.", { NULL, NULL, NULL, NULL } },
    { "window.active.button.toggled.pressed.bg", TK_TEXTURE, "window.active.button.pressed.bg", 0, 0, "Specifies the default background for titlebar buttons if the user is pressing them with the mouse while they are toggled - such as when a window is maximized. This element is for the focused window. When it is parentrelative, then it uses the window.inactive.title.bg which is underneath it.", { "titlebar colors", "window.active.title.bg", "window.inactive.button.toggled.pressed.bg", NULL } },
    { "window.active.button.toggled.pressed.image.color", TK_COLOR, "window.active.button.pressed.image.color", 0, 0, "Specifies the color of the images in the titlebar buttons if they are pressed on with the mouse while they are in the toggled state - such as when a window is maximized. This element is for the focused window.", { "window.inactive.button.toggled.pressed.image.color", NULL, NULL, NULL } },
    { "window.active.button.toggled.unpressed.bg", TK_TEXTURE, "window.active.button.toggled.bg", 0, 0, "Specifies the default background for titlebar buttons when they are toggled - such as when a window is maximized. This element is for the focused window. When it is parentrelative, then it uses the window.inactive.title.bg which is underneath it.", { "titlebar colors", "window.active.title.bg", "window.inactive.button.toggled.unpressed.bg", NULL } },
    { "window.active.button.toggled.unpressed.image.color", TK_COLOR, "window.active.button.toggled.image.color", 0, 0, "Specifies the color of the images in titlebar buttons when the button is toggled - such as when a window is maximized. This element is for the focused window.", { "window.inactive.button.toggled.unpressed.image.color", NULL, NULL, NULL } },
    { "window.active.button.unpressed.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for titlebar buttons in their default, unpressed, state. This element is for the focused window. When it is parentrelative, then it uses the window.active.title.bg which is underneath it.", { "titlebar colors", "window.active.title.bg", "window.inactive.button.unpressed.bg", NULL } },
    { "window.active.button.unpressed.image.color", TK_COLOR, "#000000", 0, 0, "Specifies the color of the images in titlebar buttons in their default, unpressed, state. This element is for the focused window.", { "window.inactive.button.unpressed.image.color", NULL, NULL, NULL } },
    { "window.active.client.color", TK_COLOR, "#FFFFFF", 0, 0, "Specifies the color of the inner border for the focused window, drawn around the window but inside the other decorations.", { "window.client.padding.width", "window.inactive.client.color", NULL, NULL } },
    { "window.active.grip.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for the focused window's grips. The grips are located at the left and right sides of the window's handle. When it is parentrelative, then it uses the window.active.handle.bg which is underneath it.", { "window.handle.width", "window.inactive.grip.bg", "window.active.handle.bg", NULL } },
    { "window.active.handle.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for the focused window's handle. The handle is the window decorations placed on the bottom of windows.", { "window.handle.width", "window.inactive.handle.bg", NULL, NULL } },
    { "window.active.label.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for the focused window's titlebar label. The label is the container for the window title. When it is parentrelative, then it uses the window.active.title.bg which is underneath it.", { "titlebar colors", "window.inactive.label.bg", "window.active.title.bg", NULL } },
    { "window.active.label.text.color", TK_COLOR, "#000000", 0, 0, "Specifies the color of the titlebar text for the focused window.", { "window.inactive.label.text.color", NULL, NULL, NULL } },
    { "window.active.label.text.font", TK_FONT_SHADOW, "shadow=n", 0, 0, "Specifies the shadow for the focused window's title.", { "window.inactive.label.text.font", NULL, NULL, NULL } },
    { "window.active.title.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for the focused window's titlebar.", { "window.inactive.title.bg", NULL, NULL, NULL } },
    { "window.active.title.separator.color", TK_COLOR, "window.active.border.color", 0, 0, "Specifies the border color for the border between the titlebar and the window, for the focused window.", { "window.inactive.title.separator.color", NULL, NULL, NULL } },
    { "window.client.padding.height", TK_INT, "window.client.padding.width", 0, 100, "Specifies the size of the top and bottom sides of the inner border. The inner border is drawn around the window, but inside the other decorations.", { "window.active.client.color", "window.inactive.client.color window.client.padding.width", NULL, NULL } },
    { "window.client.padding.width", TK_INT, "padding.width", 0, 100, "Specifies the size of the left and right sides of the inner border. The inner border is drawn around the window, but inside the other decorations.", { "window.active.client.color", "window.inactive.client.color window.client.padding.height", NULL, NULL } },
    { "window.handle.width", TK_INT, "6", 0, 100, "Specifies the size of the window handle. The window handle is the piece of decorations on the bottom of windows. A value of 0 means that no handle is shown.", { "window.active.handle.bg", "window.inactive.handle.bg", "window.active.grip.bg", "window.inactive.grip.bg" } },
    { "window.inactive.border.color", TK_COLOR, "window.active.border.color", 0, 0, "Specifies the border color for all non-focused windows.", { "border.width", "window.active.border.color", NULL, NULL } },
    { "window.inactive.button.disabled.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for titlebar buttons when they are disabled for the window. This element is for non-focused windows. When it is parentrelative, then it uses the window.inactive.title.bg which is underneath it.", { "titlebar colors", "window.inactive.title.bg", "window.active.button.disabled.bg", NULL } },
    { "window.inactive.button.disabled.image.color", TK_COLOR, "#000000", 0, 0, "Specifies the color of the images in titlebar buttons when they are disabled for the window. This element is for non-focused windows.", { "window.active.button.disabled.image.color", NULL, NULL, NULL } },
    { "window.inactive.button.hover.bg", TK_TEXTURE, "window.inactive.button.unpressed.bg", 0, 0, "Specifies the background for titlebar buttons when the mouse is over them. This element is for non-focused windows. When it is parentrelative, then it uses the window.inactive.title.bg which is underneath it.", { "titlebar colors", "window.inactive.title.bg", "window.active.button.hover.bg", NULL } },
    { "window.inactive.button.hover.image.color", TK_COLOR, "window.inactive.button.unpressed.image.color", 0, 0, "Specifies the color of the images in titlebar buttons when the mouse is over top of the button. This element is for non-focused windows.", { "window.active.button.hover.image.color", NULL, NULL, NULL } },
    { "window.inactive.button.pressed.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for titlebar buttons when they are being pressed by the user. This element is for non-focused windows. When it is parentrelative, then it uses the window.inactive.title.bg which is underneath it.", { "titlebar colors", "window.inactive.title.bg", "window.active.button.pressed.bg", NULL } },
    { "window.inactive.button.pressed.image.color", TK_COLOR, "window.inactive.button.unpressed.image.color", 0, 0, "Specifies the color of the images in titlebar buttons when they are being pressed by the user. This element is for non-focused windows.\nThis color is also used for pressed color when the button is toggled.", { "window.active.button.pressed.image.color", NULL, NULL, NULL } },
    { "window.inactive.button.toggled.bg", TK_TEXTURE, "window.inactive.button.pressed.bg", 0, 0, "This property is obsolete and only present for backwards compatibility.", { NULL, NULL, NULL, NULL } },
    { "window.inactive.button.toggled.hover.bg", TK_TEXTURE, "window.inactive.button.toggled.unpressed.bg", 0, 0, "Specifies the default background for titlebar buttons if the user is pressing them with the mouse while they are toggled - such as when a window is maximized. This element is for non-focused windows. When it is parentrelative, then it uses the window.inactive.title.bg which is underneath it.", { "titlebar colors", "window.inactive.title.bg", "window.active.button.toggled.hover.bg", NULL } },
    { "window.inactive.button.toggled.hover.image.color", TK_COLOR, "window.inactive.button.toggled.unpressed.image.color", 0, 0, "Specifies the color of the images in the titlebar buttons when the mouse is hovered over them while they are in the toggled state - such as when a window is maximized. This element is for non-focused windows.", { "window.active.button.toggled.hover.image.color", NULL, NULL, NULL } },
    { "window.inactive.button.toggled.image.color", TK_COLOR, "window.active.button.pressed.image.color", 0, 0, "This property is obsolete and only present for backwards compatibility.", { NULL, NULL, NULL, NULL } },
    { "window.inactive.button.toggled.pressed.bg", TK_TEXTURE, "window.inactive.button.pressed.bg", 0, 0, "Specifies the default background for titlebar buttons if the user is pressing them with the mouse while they are toggled - such as when a window is maximized. This element is for non-focused windows. When it is parentrelative, then it uses the window.inactive.title.bg which is underneath it.", { "titlebar colors", "window.inactive.title.bg", "window.active.button.toggled.pressed.bg", NULL } },
    { "window.inactive.button.toggled.pressed.image.color", TK_COLOR, "window.inactive.button.pressed.image.color", 0, 0, "Specifies the color of the images in the titlebar buttons if they are pressed on with the mouse while they are in the toggled state - such as when a window is maximized. This element is for non-focused windows.", { "window.active.button.toggled.pressed.image.color", NULL, NULL, NULL } },
    { "window.inactive.button.toggled.unpressed.bg", TK_TEXTURE, "window.inactive.button.toggled.bg", 0, 0, "Specifies the default background for titlebar buttons when they are toggled - such as when a window is maximized. This element is for non-focused windows. When it is parentrelative, then it uses the window.inactive.title.bg which is underneath it.", { "titlebar colors", "window.inactive.title.bg", "window.active.button.toggled.unpressed.bg", NULL } },
    { "window.inactive.button.toggled.unpressed.image.color", TK_COLOR, "window.inactive.button.toggled.image.color", 0, 0, "Specifies the color of the images in titlebar buttons when the button is toggled - such as when a window is maximized. This element is for non-focused windows.", { "window.active.button.toggled.unpressed.image.color", NULL, NULL, NULL } },
    { "window.inactive.button.unpressed.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for titlebar buttons in their default, unpressed, state. This element is for non-focused windows. When it is parentrelative, then it uses the window.inactive.title.bg which is underneath it.", { "titlebar colors", "window.inactive.title.bg", "window.active.button.unpressed.bg", NULL } },
    { "window.inactive.button.unpressed.image.color", TK_COLOR, "#FFFFFF", 0, 0, "Specifies the color of the images in titlebar buttons in their default, unpressed, state. This element is for non-focused windows.", { "window.active.button.unpressed.image.color", NULL, NULL, NULL } },
    { "window.inactive.client.color", TK_COLOR, "#FFFFFF", 0, 0, "Specifies the color of the inner border for non-focused windows, drawn around the window but inside the other decorations.", { "window.client.padding.width", "window.active.client.color", NULL, NULL } },
    { "window.inactive.grip.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for non-focused windows' grips. The grips are located at the left and right sides of the window's handle. When it is parentrelative, then it uses the window.inactive.handle.bg which is underneath it.", { "window.handle.width", "window.active.grip.bg", "window.inactive.handle.bg", NULL } },
    { "window.inactive.handle.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for non-focused windows' handles. The handle is the window decorations placed on the bottom of windows.", { "window.handle.width", "window.active.handle.bg", NULL, NULL } },
    { "window.inactive.label.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for non-focused windows' titlebar labels. The label is the container for the window title. When it is parentrelative, then it uses the window.inactive.title.bg which is underneath it.", { "titlebar colors", "window.active.label.bg", "window.inactive.title.bg", NULL } },
    { "window.inactive.label.text.color", TK_COLOR, "#FFFFFF", 0, 0, "Specifies the color of the titlebar text for non-focused windows.", { "window.active.label.text.color", NULL, NULL, NULL } },
    { "window.inactive.label.text.font", TK_FONT_SHADOW, "shadow=n", 0, 0, "Specifies the shadow for non-focused windows' titles.", { "window.active.label.text.font", NULL, NULL, NULL } },
    { "window.inactive.title.bg", TK_TEXTURE, "none", 0, 0, "Specifies the background for non-focused windows' titlebars.", { "window.active.title.bg", NULL, NULL, NULL } },
    { "window.inactive.title.separator.color", TK_COLOR, "window.inactive.border.color", 0, 0, "Specifies the border color for the border between the titlebar and the window, for non-focused windows.", { "window.active.title.separator.color", NULL, NULL, NULL } },
    { "window.label.text.justify", TK_JUSTIFY, "Left", 0, 0, "Specifies how window titles are aligned in the titlebar for both the focused and non-focused windows.", { NULL, NULL, NULL, NULL } },
};

const guint THEME_SCHEMA_COUNT = G_N_ELEMENTS(THEME_SCHEMA);

const ThemeKeySpec *schema_find(const char *key)
{
    guint i;
    for (i = 0; i < THEME_SCHEMA_COUNT; ++i)
        if (strcmp(THEME_SCHEMA[i].key, key) == 0)
            return &THEME_SCHEMA[i];
    return NULL;
}
